version: '3.8'

services:
  api_service:
    container_name: api_service
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/cycleShop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=chaitanya
      - SPRING_DATASOURCE_PASSWORD=chaitanya

  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cycleShop
      MYSQL_USER: chaitanya
      MYSQL_PASSWORD: chaitanya